FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o agent cmd/agent/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/agent .

CMD ["./agent"]
